import turtle

turtle.shape('turtle')
turtle.color('yellow')
turtle.begin_fill()
turtle.circle(100)
turtle.end_fill()
turtle.color('black')
turtle.penup()
turtle.goto(0,70)
turtle.pendown()
turtle.width(9)
turtle.left(90)
turtle.forward(25)
turtle.color('blue')
turtle.penup()
turtle.goto(50,150)
turtle.pendown()
turtle.begin_fill()
turtle.circle(10)
turtle.end_fill()
turtle.penup()
turtle.goto(-30,150)
turtle.pendown()
turtle.begin_fill()
turtle.circle(10)
turtle.end_fill()
turtle.penup()
turtle.goto(-20,20)
turtle.pendown()
turtle.circle(-20, 180, 20)
